-- sql/db/schema.sql

-- Drop existing tables (in reverse dependency order)
DROP TABLE IF EXISTS MACRO.REGIMES_GLOBAL CASCADE;
DROP TABLE IF EXISTS MACRO.FEATURES CASCADE;
DROP TABLE IF EXISTS MACRO.RAW_SERIES CASCADE;
DROP TABLE IF EXISTS MACRO.INGEST_LOG CASCADE;

-- Drop and recreate schema
DROP SCHEMA IF EXISTS MACRO CASCADE;
CREATE SCHEMA MACRO;

-- 1) RAW OBSERVATIONS (TICKER-LEVEL INPUTS)
-- One row per (ticker, dt)
CREATE TABLE MACRO.RAW_SERIES (
    TICKER       TEXT NOT NULL,              -- e.g. "SPX", "DGS10", "DXY", "WTI"
    ASSET_CLASS  TEXT NOT NULL,              -- e.g. "EQUITY", "RATES", "FX", "CREDIT", "COMMODITIES", "VOL"
    DT           DATE NOT NULL,
    VALUE        DOUBLE PRECISION,
    SOURCE       TEXT NOT NULL,              -- e.g. "FRED", "YAHOO"
    INGESTED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (TICKER, DT)
);

CREATE INDEX IDX_RAW_SERIES_DT
    ON MACRO.RAW_SERIES (DT);

CREATE INDEX IDX_RAW_SERIES_ASSET_CLASS
    ON MACRO.RAW_SERIES (ASSET_CLASS);


-- 2) FEATURES (DERIVED; VERSIONED)
-- for global features, set TICKER='GLOBAL' and ASSET_CLASS='MACRO'.
CREATE TABLE MACRO.FEATURES (
    DT           DATE NOT NULL,
    TICKER       TEXT NOT NULL,              -- e.g. "SPX" or "GLOBAL"
    ASSET_CLASS  TEXT NOT NULL,              -- e.g. "EQUITY" or "MACRO"
    FEATURE      TEXT NOT NULL,              -- e.g. "SPX_RET_20D", "VIX_LEVEL", "CREDIT_SPREAD_Z"
    VALUE        DOUBLE PRECISION,
    VERSION      TEXT NOT NULL,              -- e.g. "V1_BASELINE"
    COMPUTED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (DT, TICKER, FEATURE, VERSION)
);

CREATE INDEX IDX_FEATURES_DT
    ON MACRO.FEATURES (DT);

CREATE INDEX IDX_FEATURES_FEATURE
    ON MACRO.FEATURES (FEATURE);

CREATE INDEX IDX_FEATURES_TICKER
    ON MACRO.FEATURES (TICKER);


-- 3) GLOBAL REGIMES (MARKET-WIDE OUTPUT; VERSIONED)
-- One regime per date per version. Not ticker-specific.
CREATE TABLE MACRO.REGIMES_GLOBAL (
    DT          DATE NOT NULL,
    REGIME      TEXT NOT NULL,               -- e.g. "RISK_ON", "RISK_OFF", "INFLATION_SHOCK"
    SCORE       DOUBLE PRECISION,            -- confidence/probability/margin
    VERSION     TEXT NOT NULL,               -- e.g. "V0_RULES", "V1_HMM"
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (DT, VERSION)
);

CREATE INDEX IDX_REGIMES_GLOBAL_DT
    ON MACRO.REGIMES_GLOBAL (DT);

CREATE INDEX IDX_REGIMES_GLOBAL_REGIME
    ON MACRO.REGIMES_GLOBAL (REGIME);


-- 4) INGEST LOG (TRACKING & DEBUGGING)
-- Tracks each ingestion run for monitoring and troubleshooting
CREATE TABLE MACRO.INGEST_LOG (
    RUN_ID       TEXT NOT NULL,               -- unique identifier for this run (e.g. timestamp)
    STARTED_AT   TIMESTAMP NOT NULL DEFAULT NOW(),
    FINISHED_AT  TIMESTAMP,                   -- null until run completes
    STATUS       TEXT NOT NULL,               -- 'running', 'ok', 'failed'
    MESSAGE      TEXT,                        -- optional details/error messages

    PRIMARY KEY (RUN_ID)
);

CREATE INDEX IDX_INGEST_LOG_STARTED_AT
    ON MACRO.INGEST_LOG (STARTED_AT);

CREATE INDEX IDX_INGEST_LOG_STATUS
    ON MACRO.INGEST_LOG (STATUS);