-- sql/db/schema.sql

CREATE SCHEMA IF NOT EXISTS MACRO;

-- 1) RAW OBSERVATIONS (TICKER-LEVEL INPUTS)
-- One row per (ticker, dt)
CREATE TABLE IF NOT EXISTS MACRO.RAW_SERIES (
    TICKER       TEXT NOT NULL,              -- e.g. "SPX", "DGS10", "DXY", "WTI"
    ASSET_CLASS  TEXT NOT NULL,              -- e.g. "EQUITY", "RATES", "FX", "CREDIT", "COMMODITIES", "VOL"
    DT           DATE NOT NULL,
    VALUE        DOUBLE PRECISION,
    SOURCE       TEXT NOT NULL,              -- e.g. "FRED", "YAHOO"
    INGESTED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (TICKER, DT)
);

CREATE INDEX IF NOT EXISTS IDX_RAW_SERIES_DT
    ON MACRO.RAW_SERIES (DT);

CREATE INDEX IF NOT EXISTS IDX_RAW_SERIES_ASSET_CLASS
    ON MACRO.RAW_SERIES (ASSET_CLASS);


-- 2) FEATURES (DERIVED; VERSIONED)
-- for global features, set TICKER='GLOBAL' and ASSET_CLASS='MACRO'.
CREATE TABLE IF NOT EXISTS MACRO.FEATURES (
    DT           DATE NOT NULL,
    TICKER       TEXT NOT NULL,              -- e.g. "SPX" or "GLOBAL"
    ASSET_CLASS  TEXT NOT NULL,              -- e.g. "EQUITY" or "MACRO"
    FEATURE      TEXT NOT NULL,              -- e.g. "SPX_RET_20D", "VIX_LEVEL", "CREDIT_SPREAD_Z"
    VALUE        DOUBLE PRECISION,
    VERSION      TEXT NOT NULL,              -- e.g. "V1_BASELINE"
    COMPUTED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (DT, TICKER, FEATURE, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_FEATURES_DT
    ON MACRO.FEATURES (DT);

CREATE INDEX IF NOT EXISTS IDX_FEATURES_FEATURE
    ON MACRO.FEATURES (FEATURE);

CREATE INDEX IF NOT EXISTS IDX_FEATURES_TICKER
    ON MACRO.FEATURES (TICKER);


-- 3) GLOBAL REGIMES (MARKET-WIDE OUTPUT; VERSIONED)
-- One regime per date per version. Not ticker-specific.
CREATE TABLE IF NOT EXISTS MACRO.REGIMES_GLOBAL (
    DT          DATE NOT NULL,
    REGIME      TEXT NOT NULL,               -- e.g. "RISK_ON", "RISK_OFF", "INFLATION_SHOCK"
    SCORE       DOUBLE PRECISION,            -- optional: confidence/probability/margin
    VERSION     TEXT NOT NULL,               -- e.g. "V0_RULES", "V1_HMM"
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (DT, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_REGIMES_GLOBAL_DT
    ON MACRO.REGIMES_GLOBAL (DT);

CREATE INDEX IF NOT EXISTS IDX_REGIMES_GLOBAL_REGIME
    ON MACRO.REGIMES_GLOBAL (REGIME);